services:
  client:
    build: client
    ports:
      - "12897:80"
    volumes:
      - ./blogs:/var/www/blogs
      - ./sites:/var/www/sites
    depends_on:
      - server

  server:
    build: server
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=mainpage
    depends_on:
      - mysql
  
  uploader:
    build: uploader
    volumes:
      - ./blogs:/var/blogs
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=mainpage
    depends_on:
      - mysql
  
  mysql:
    image: "mysql"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mainpage